[package]
name = "osirisdb"
version = "0.6.0"
edition = "2024"
authors = ["Musab Khan <musab05ahs@gmail.com>"]
description = "A SQL database engine built from scratch in Rust featuring a custom parser, binder, query planner, optimizer, catalog, and storage engine."
license = "Apache-2.0"
repository = "https://github.com/musab05/osirisdb"
homepage = "https://github.com/musab05/osirisdb"
documentation = "https://docs.rs/osirisdb"
readme = "README.md"
keywords = ["sql", "database", "dbms", "query-engine", "rust"]
categories = ["parser-implementations", "database"]
rust-version = "1.91.1"

[dependencies]

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "catalog_bench"
path = "benches/catalog_bench.rs"
harness = false

[[bench]]
name = "lexer_bench"
path = "benches/lexer/database_bench.rs"
harness = false

[[bench]]
name = "parser_bench"
path = "benches/parser/database_bench.rs"
harness = false

[[bench]]
name = "binder_bench"
path = "benches/binder_bench.rs"
harness = false

[[bench]]
name = "executor_bench"
path = "benches/executor_bench.rs"
harness = false

[[bench]]
name = "storage_bench"
path = "benches/storage/database_bench.rs"
harness = false